### ISSUE TITLE
We should have a channelnumber translator?

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/MATS-L1-processing#1]
In some parts of the code the channels are reffered to via their number 1-7 sometimes with their name e.g. "UV1" and sometimes with the CCDID. Should we have a functions which translates between them?

**Comment by OleMartinChristensen** [comment]
We should test the code with digital gain not 1 (FPGA binning)

**Comment by lindamegner** [comment]
This is sort of done in the CCD class. It may be that we want to add other ways to name the channels later, but for now their naming as it comes out of the rac files are translated to a string so that they are named for instance 'IR1', 'UV2'. I figure we better use a string names rather than numbers since we have give them so many differet number names, the string names are difficult to misinterpret.

**Comment by OleMartinChristensen** [comment]
agreed looks like its done in the CCDclass
