### ISSUE TITLE
L1b data men ingen L1a data

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/MATS-L1-processing#195]
Vi verkar ha l1b data för vissa perioder där vi saknar l1a.   Snippet 1 ger en dataframe med längd 237 men snippet 2 ger noll.
Nån som fattar varför?

Snippet 1:
start_time=DT.datetime(2023,5,7,1,0,0)
stop_time=DT.datetime(2023,5,7,2,0,0)
filter_UV2={'CCDSEL': [6,6]} 
df=read_MATS_data(start_time, stop_time, filter_UV2, level='1b')

Snippet  2:
start_time=DT.datetime(2023,5,7,1,0,0)
stop_time=DT.datetime(2023,5,7,2,0,0)
filter_UV2={'CCDSEL': [6,6]} 
df=read_MATS_data(start_time, stop_time, filter_UV2, level='1a')

**Comment by OleMartinChristensen** [comment]
1: this comment should be in the MATS-Analysis repo (where read data is located)

2: The reason is that per default version for data is v0.4 and there is no v0.4 for that date. Try change to read_MATS_data(start_time, stop_time, filter_UV2, level='1a',version='0.6') I also reccomend using version = '0.5' for the level 1b data

**Comment by lindamegner** [comment]
ok got it
