### ISSUE TITLE
Cannot get pytest to run

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/MATS-L1-processing#4]
I cannot get pytest to run successfully. I have downloaded the directory 210215OHBLimbImage and ran rac extract v0.2.4 on it. But I get the error Exception: Image 6282658599854_3 in protocol but not found in rac file

**Comment by lindamegner** [comment]
Added directory 210215OHBLimbImage in     CalibrationSoftware >  software_data > testdata on box. If that is added to testdata it sould run.  Still TODO - check why it did not run with the files you extracted from rac.

**Comment by lindamegner** [comment]
Answer to TODO from last comment: The reason why the file did not run whey you extracted the files from rac  was not due to the change in naming as we thought. It is becasue the protocol 'protocol_dark_bright_100um_incl_IR3.txt' reads the IR3 images from a different date (since IR3 was not functioning when the other images were taken) and those IR3-images had been hand copied into the RacFiles_out directory. This is not optimal but on the other hand it should not cause any problem so I leave it as it is. That is, use the directory that is in testdata on box.
